server:
  port: 8800
spring:
  application:
    name: eureka-provider
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrlPath: ${management.context-path:}/info
    healthCheckUrlPath: ${management.context-path:}/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8000
#spring:
#  application:
#    name: microservice-provider-user
#
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
#  instance:
#    preferIpAddress: true
#